### ISSUE TITLE
Some app errors

### ISSUE THREAD

**Issue by roberttodor** [wq/wq.start#6]
I create a simple project and build the apk with Phonegap.  
I installed the app in my android device and found  this issues:
Failed to load resource: net::ERR_FILE_NOT_FOUND pginit.js:1 
Failed to load resource: net::ERR_FILE_NOT_FOUND require.js

Serving the app into a browser, it looks to work fine but I tried to stop server and Submit.   After that, I started server again, but the item  dosen't Sync automatically. Also the Sync Now and Discard buttons  fails with this error :
Uncaught ReferenceError: require is not defined
    at HTMLButtonElement.onclick ((index):1)

**Comment by sheppard** [comment]
I fixed the issues with the Sync Now and Discard buttons when running an npm-based app in the browser.   I published the fix in wq.start 1.2.1.   However, the issues with PhoneGap remain unresolved - see wq/wq.app#121 for more info.
